[workspace]
authors = ["Gwendal Crequer <gwendal.crequer@laas.fr>"]
channels = ["conda-forge"]
name = "VIBES"
platforms = ["linux-64"]
version = "0.2.0"
preview = ["pixi-build"]

[tasks]
configure = "cmake -B build -S ."
build = { cmd = "cmake --build build", depends-on = ["configure"] }
install = { cmd = "cmake --install build", depends-on = ["build"] }
clean = "rm -rf build"

[dependencies]
vibes = { path = "." }

[package]
name = "vibes"
version = "0.2.0"


[package.build]
backend = { name = "pixi-build-cmake", version = "0.3.*", channels = ["https://prefix.dev/pixi-build-backends", "conda-forge"] }

[package.build.config]
extra-args = ["-DCMAKE_BUILD_TYPE=Release"]

[package.host-dependencies]
qt6-main = "*"
mesalib = ">*"
cmake = "*"
git = ">=*"
cxx-compiler = "*"

[package.build-dependencies]
git = "*"